sql:
  host: "13.59.44.163"
  port: 5432
  db: "flibo"
  schema: "app"
  user: "postgres"
  password: "ClickOpenYzal123"

prerendered_htmls_directory: "./prerendered_htmls/"
build_hashes:
  data_1: "data-v-742ff8a2"
  data_2: "data-v-a3bb3e6a"
  js:
    app: "8cd36b78"
    home: "819050fd"
    article: "f83958da"
    article_on_demand: "6e852eeb"
    chunk_vendors: "757b39db"
  css:
    app: "37cc0440"
    home: "9b330532"
    article: "937078cc"
    article_on_demand: "0f8f0545"
    chunk_vendors: "f5c5c5f0"
  img:
    flibo_ad: "a31dbb19"

sitemaps:
  directory: "./sitemaps/"
  url_limit: 25000
  date: "2021-02-14"
